#!/usr/bin/env python

from zensols.cli import ConfigurationImporterCliHarness


def turn_off_huggingface_downloads():
    import os
    os.environ['TRANSFORMERS_OFFLINE'] = '1'


if (__name__ == '__main__'):
    turn_off_huggingface_downloads()
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        package_resource='zensols.clinicamr',
        config_path='etc/clinicamr.conf',
        proto_args={0: 'proto',
                    1: 'proto --override amr_default.parse_model=gsii'
                    }[0],
        proto_factory_kwargs={'reload_pattern': r'^zensols.clinicamr'},
    )
    harness.run()
